config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'patients#new'

  resources :patients, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/patient.rb
class Patient < ApplicationRecord

  attribute :patient_file

  class << self
    def basic_search(search_string)
      all.where("patients.name ILIKE ?", "%#{search_string}%")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def xhr_redirect_to(args)
    @args = args
    flash.keep
    render 'shared/xhr_redirect_to'
  end

end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController

  def index
    @patients = Patient.all
    if params[:search_query].present?
      @patients = @patients.basic_search(params[:search_query])
    end
  end

  def new
    @patient = Patient.new
  end

  def create
    require "csv"
    @success=[]
    @errors=[]
    CSV.foreach(patient_params[:patient_file].tempfile, {:headers=>:first_row, :encoding=> "iso-8859-1:utf-8"}) do |row|
      patient_name = row["name"]&.strip
      patient_date = Date.parse(row["date"]&.strip)
      patient_number = row["number"]&.strip&.to_i
      description = row["description"]
      patient = Patient.new(
        name: patient_name,
        date: patient_date,
        number: patient_number,
        description: description,
      )
      if patient.save
        @success << {patient_name: row["name"], message: ["success"]}
      else
        @errors << {patient_name: row["name"], message: patient.errors.full_messages.join(",")}
      end
    end
  end

  private

  def patient_params
    params.require(:patient).permit(
      :patient_file
    )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title EmployeeUpload
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag "http://code.jquery.com/jquery-1.11.0.min.js"
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    %script{:src => "https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.19/js/jquery.dataTables.min.js"}
    %script{:src => "https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"}
    %script{:src => "https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"}
  %body
    = yield

app/views/patients/create.html.haml
%center
  .panel.panel-primary
    .panel-footer
      %strong
        Failures (#{@errors.count}):
      %br/
      %ul
        - @errors.each do |error|
          %li
            %strong{:style => "color: #f00"}
              = "#{error[:patient_name]}" " - " "#{error[:message]}"
      %br/
      %br/
      %strong
        Successful (#{@success.count}):
      %br/
      %ul
        - @success.each do |success|
          %li
            %strong{:style => "color: #008a1a"}
              = "#{success[:patient_name]}"
      %p
        Please Click Here To See Imported Patient
        = link_to 'Imported Patient', patients_path

app/views/patients/index.html.haml
.content-wrapper
  .content-header
    .container-fluid
      .row.mb-2
        .col-sm-12
          %ol.breadcrumb
            %li.breadcrumb-item
              %a{:href => root_path} Home
            %li.breadcrumb-item.active
              Patients
  .w-100
  .content-wrapper
    .content-header
      .container-fluid
        .row
          .col-sm-12
            .col-md-3
              .input-group
                .input-group-btn
                  = link_to 'Add New Patients', new_patient_path,
                    class: 'btn btn-primary float-right btn-sm'
            %br
            .col-md-4
              = form_tag patients_path, method: :get do
                .input-group.input-group-sm
                  = text_field_tag :search_query, params[:search_query], class: "form-control", placeholder: "Search by name"
                  = button_tag type: "submit", class: "btn btn-primary btn-sm" do
                    = fa_icon "search"
                  = link_to patients_path, class: "btn btn-primary btn-sm" do
                    = fa_icon "refresh"
            %br
  .content
    .container-fluid
      .row
        .col-lg-12
          .card
            .card-body
              .table-responsive
                %table.table.table-bordered.table-hover.dataTables.table-sm.responsive.nowrap{style: 'width:100%!important'}
                  %thead
                    %tr
                      %th.all #
                      %th.all Name
                      %th.all Date
                      %th.desktop Number
                      %th.desktop Description
                  %tbody
                    - @patients.each.with_index(1) do |patient, i|
                      %tr
                        %td= i
                        %td= patient.name
                        %td= patient.date.strftime("%d %B %Y")
                        %td= patient.number
                        %td= patient.description

app/views/patients/new.html.haml
.content-wrapper
  .content-header
    .container-fluid
      .row.mb-2
        .col-sm-12
          %ol.breadcrumb
            %li.breadcrumb-item
              %a{:href => root_path} Home
            %li.breadcrumb-item
              = link_to "Patients", patients_path
            %li.breadcrumb-item.active
              New
        .col-sm-12
          %h1.m-0.text-dark
            New Patient
  .content
    .container-fluid
      .row
        .col-md-12
          .card
            .card-body
              = bootstrap_form_for [@patient], layout: :horizontal, label_col: 'col-md-12', control_col: 'col-md-12' do |f|
                .modal-body
                  .row
                    .col-sm-12.required
                      .form-group
                        .form-group.col-md-12
                          .form-group.col-md-12.mb-3.p-0
                            .input-group
                              .custom-file
                                = f.file_field :patient_file, accept: 'text/csv', :class=>"custom-file-input", label: 'Choosen Patient File', :required=>true
                  = f.submit 'Submit Patient', class: 'btn btn-success'

app/views/shared/xhr_redirect_to.js.erb
$(document).ajaxStop(function() {
  $('input[type=submit]').attr('disabled', true);
});
validNavigation = true;
var redirectUrl;
redirectUrl = '<%= @args[:redirect_to] %>';
window.location.href = redirectUrl.length ? redirectUrl : window.location.href;